### ISSUE TITLE
Question about using my own data

### ISSUE THREAD

**Issue by lotfielhafi** [chrisgundling/yolo_light#1]
@chrisgundling Thank you for sharing your work. I am also very interested in a ROS implementation of Darkflow and I have several questions regarding the retraining with my own data.

Until now, I have been using Darkflow to train my own classes from custom data and config file to obtain custom checkpoint files. Can I use them with your ROS node as an input to detect object from a USB camera?

Also, what is the output (topic) of your node? Do you provide any launch file? And finally, is it compatible with Xenial/Kinetic?

Thank you.

**Comment by chrisgundling** [comment]
@lotfielhafi Lotfi,

Thanks for your interest. Several things to address here:
1. The implementation here is very similar to yours, re-trained Darkflow model on a new dataset with new classes. This was done with custom config file and led to custom weights (checkpoint).
2. My ROS node subscribes to an "Image" topic that is produced from replayed .bag files of images collected from a vehicle camera. It then modifies that image, by predicting the bounding boxes and drawing them with opencv. The modified image is then published to a new "Image" topic. I don't know much about USB cameras, but if you can publish an "Image" topic (raw data) or a "CompressedImage" topic of video from the camera, then you can use this ROS node to subscribe to that topic and publish the boxed image.
3. You will have to make some modifications inside of (/scripts/net/flow.py) in order to draw the bounding boxes for all or a selected set of your classes. I currently have it setup to only draw boxes on the single "traffic light" class.
4. There is no launch file, but if you just clone and build this package in your ROS workspace, it should work with the commands in the README.md. I actually went through these steps as a test myself to re-build the package, so hopefully it works for you.
5. Yes, Xenial/Kinetic is what I used. 

I'm happy to help if you run into any issues, so just let me know.

Chris

**Comment by lotfielhafi** [comment]
@chrisgundling Thank you for your help. For the record, I was able to run your package in Xenial/Kinetic and, after some modifications, use an Intel RealSense R200 as an input, publish the detections to draw them in an OpenCV window and write a launch file to start everything using the .cgf and ckpt files you provided. I am now trying to use it with the VOC database to detect non driving-related objects. I will keep you updated :-)

If anyone needs help for a usecase similar to mine, please ask me.
